name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
   build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [15]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Setup
      run: npm i -g @antfu/ni

    - name: Install
      run: nci

    - name: Build
      run: nr build
